const mess = [
    {
        idMessemger:1,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'Hello',
        createdAt: new Date(),
        sent:1,
        received:1,


    },
    {
        idMessemger:2,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:3,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'IMAGE',
        urlImage:require('./assets/image/anh4.jpg'),
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:4,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:5,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:6,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:7,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:8,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'hello',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:9,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'hii',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:10,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'ok ok nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    //tao 5 chat nua
    {
        idMessemger:11,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'Hello',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:12,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:13,
        user:{
            _id:1,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./assets/images/avatar.jpg',
        },
        receiver:{
            _id:2,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'IMAGE',
        urlImage:require('./assets/image/anh4.jpg'),
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:14,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:15,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./src/assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'TEXT',
        messengerContent:'alo alo nhan dep trai so 1 the gioi alo alo nhan dep trai so 1 the gioi alo alo nhan dep trai so 1 the gioi alo alo nhan dep trai so 1 the gioi',
        createdAt: new Date(),
        sent:1,
        received:1,
    },
    {
        idMessemger:16,
        user:{
            _id:2,
            nameUserSend:'Phạm Đức Nhân',
            avatarUserSend:'./assets/images/avatar.jpg',
        },
        receiver:{
            _id:1,
            nameReceiver:'Nguyễn Nhật Sang',
            avatarReceiver:require('./assets/image/avt2.png'),
        },
        messengerType:'IMAGE',
        urlImage:require('./assets/image/anh4.jpg'),
        createdAt: new Date(),
        sent:1,
        received:1,
    }
]

export default mess;