export default {
    primary:'rgba(238, 102, 25, 1)',
    white: 'white',
    black: 'black',
    grey: 'grey',
    lightGrey: 'lightgrey',
    darkGrey: 'darkgrey',
    red: 'red',
    green: 'green',
    blue: 'blue',
    lightBlue: 'lightblue',
    darkBlue: 'darkblue',
    yellow: 'yellow',
    lightYellow: 'lightyellow',
    darkYellow: 'darkyellow',
    orange: 'orange',
    lightOrange: 'lightorange',
    darkOrange: 'darkorange',
    purple: 'purple',
    lightPurple: 'lightpurple',
    darkPurple: 'darkpurple',
    backgroundChat: 'rgba(0,0,0,0.90)',
    bubble :'rgba(143, 79, 42, 1)'
}